package:
  name: mandelbrot-demo
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  entry_points:
    - mandelbrot =mandelbrot_demo.mandelbrot:main
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python

test:
  requires:
    - pytest =7.1.2
  imports:
    - mandelbrot_demo

requirements:
  build:
    - python
    - pygame
    - numpy
    #- git
    #- wheel =0.38.4
    #- setuptools =65.6.3
  host:
    #- python
    #- pip

  run:
    #- python
    - numpy <1.24
    #- numba >=0.56.4
    #- dpnp
    #- dpctl
    #- numba-dpex
    #- pygame =2.3.0

about:
  home: https://github.com/samaid/mandelbrot
  summary: Mandelbrot Set demo with `numpy`, `numba`, `dpnp`, `numba-dpex`.
  description: |
    Mandelbrot description
  license: BSD-2
  license_file: LICENSE
