package:
  name: mandelbrot-demo
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  entry_points:
    - mandelbrot =mandelbrot_demo.mandelbrot:main
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - WHEELS_OUTPUT_FOLDER

test:
  requires:
    - pytest =7.1.2
    - pytest-cov
    - pytest-mock =3.10.0
    - numpy <1.24
    - numba >=0.56.4
    - dpnp
    - dpctl
    - numba-dpex

  imports:
    - mandelbrot_demo

requirements:
  build:
  host:
    - python
    - setuptools =65.6.3
    - git
    - wheel =0.38.4
    - numpy
    - numba >=0.56.4
    - matplotlib
    - dpnp
    - dpctl
    - numba-dpex

  run:
    - python
    - numpy <1.24
    - numba >=0.56.4
    - pygame
    - dpnp
    - dpctl
    - numba-dpex

about:
  home: https://github.com/samaid/mandelbrot
  summary: Mandelbrot Set demo with `numpy`, `numba`, `dpnp`, `numba-dpex`.
  description: |
    Mandelbrot description
  license: BSD-2
  license_file: LICENSE
